version: "3.7"
services: 
  
  orcl18c:
    build: 
      context: .
    environment:
      ORACLE_PWD: System#1 
      TZ: America/Sao_Paulo
    volumes: 
      - ora_data:/opt/oracle/oradata
    ports: 
      - "1521:1521"

volumes: 
  ora_data:
